


















#pragma warning disable 1591
#pragma warning disable 0108
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Team Development for Sitecore.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;   
using System.Collections.Generic;   
using System.Linq;
using System.Text;
using Glass.Mapper.Sc.Configuration.Attributes;
using Glass.Mapper.Sc.Configuration;
using Glass.Mapper.Sc.Fields;
using Sitecore.Globalization;
using Sitecore.Data;

namespace MarketingVillage.Feature.Card.Models
{
	public partial interface IGlassBase{
		[SitecoreId]
		Guid Id{ get; }
		[SitecoreInfo(SitecoreInfoType.Language)]
        Language Language{ get; }
        [SitecoreInfo(SitecoreInfoType.Version)]
        int Version { get; }
	}
	public abstract partial class GlassBase : IGlassBase{
		[SitecoreId]
		public virtual Guid Id{ get; private set;}
		[SitecoreInfo(SitecoreInfoType.Language)]
        public virtual Language Language{ get; private set; }
        [SitecoreInfo(SitecoreInfoType.Version)]
        public virtual int Version { get; private set; }
		[SitecoreInfo(SitecoreInfoType.Url)]
        public virtual string Url { get; private set; }
	}
}
namespace MarketingVillage.Feature.Card.Models
{
 	/// <summary>
	/// IC01___Card Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/MarketingVillage/Feature/Card/C01 - Card</para>	
	/// <para>ID: 0046a26d-a5a2-48d0-82c9-573aed8d3c39</para>	
	/// </summary>
	[SitecoreType(TemplateId=IC01___CardConstants.TemplateIdString )] //, Cachable = true
	public partial interface IC01___Card : IGlassBase 
	{
			
					/// <summary>
					/// The Has Button field.
					/// <para></para>
					/// <para>Field Type: Checkbox</para>		
					/// <para>Field ID: 4fa7b29b-5684-463a-84e9-585371b8b3a3</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IC01___CardConstants.Has_ButtonFieldName)]
					bool Has_Button  {get; set;}
			
					/// <summary>
					/// The Has SubTitle field.
					/// <para></para>
					/// <para>Field Type: Checkbox</para>		
					/// <para>Field ID: 4e40224d-f06a-4487-a624-37209dff8786</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IC01___CardConstants.Has_SubTitleFieldName)]
					bool Has_SubTitle  {get; set;}
			
					/// <summary>
					/// The Image Is Clickable field.
					/// <para></para>
					/// <para>Field Type: Checkbox</para>		
					/// <para>Field ID: dc4ce0f7-1fb6-4102-bdf8-1a411e0622ff</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IC01___CardConstants.Image_Is_ClickableFieldName)]
					bool Image_Is_Clickable  {get; set;}
			
					/// <summary>
					/// The Title Is Clickable field.
					/// <para></para>
					/// <para>Field Type: Checkbox</para>		
					/// <para>Field ID: 44519f58-8a57-422b-b17a-d247860a8828</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IC01___CardConstants.Title_Is_ClickableFieldName)]
					bool Title_Is_Clickable  {get; set;}
			
					/// <summary>
					/// The C01 Events field.
					/// <para></para>
					/// <para>Field Type: Multilist with Search</para>		
					/// <para>Field ID: 79407ee4-aca1-45bc-9125-1ea61d6041f8</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IC01___CardConstants.C01_EventsFieldName)]
					IEnumerable<Guid> C01_Events  {get; set;}
			
					/// <summary>
					/// The C01 Goals field.
					/// <para></para>
					/// <para>Field Type: Multilist with Search</para>		
					/// <para>Field ID: 43e7f6e9-a782-4455-b131-c350438c9539</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IC01___CardConstants.C01_GoalsFieldName)]
					IEnumerable<Guid> C01_Goals  {get; set;}
			
					/// <summary>
					/// The C01 Outcome field.
					/// <para></para>
					/// <para>Field Type: Multilist with Search</para>		
					/// <para>Field ID: a155ed32-1410-485c-a7bf-df3a61094ba9</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IC01___CardConstants.C01_OutcomeFieldName)]
					IEnumerable<Guid> C01_Outcome  {get; set;}
			
	}
	public static partial class IC01___CardConstants{
			public const string TemplateIdString = "0046a26d-a5a2-48d0-82c9-573aed8d3c39";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "C01 - Card";
		
			public static readonly ID Has_ButtonFieldId = new ID("4fa7b29b-5684-463a-84e9-585371b8b3a3");
			public const string Has_ButtonFieldName = "Has Button";
		
			public static readonly ID Has_SubTitleFieldId = new ID("4e40224d-f06a-4487-a624-37209dff8786");
			public const string Has_SubTitleFieldName = "Has SubTitle";
		
			public static readonly ID Image_Is_ClickableFieldId = new ID("dc4ce0f7-1fb6-4102-bdf8-1a411e0622ff");
			public const string Image_Is_ClickableFieldName = "Image Is Clickable";
		
			public static readonly ID Title_Is_ClickableFieldId = new ID("44519f58-8a57-422b-b17a-d247860a8828");
			public const string Title_Is_ClickableFieldName = "Title Is Clickable";
		
			public static readonly ID C01_EventsFieldId = new ID("79407ee4-aca1-45bc-9125-1ea61d6041f8");
			public const string C01_EventsFieldName = "C01 Events";
		
			public static readonly ID C01_GoalsFieldId = new ID("43e7f6e9-a782-4455-b131-c350438c9539");
			public const string C01_GoalsFieldName = "C01 Goals";
		
			public static readonly ID C01_OutcomeFieldId = new ID("a155ed32-1410-485c-a7bf-df3a61094ba9");
			public const string C01_OutcomeFieldName = "C01 Outcome";
			
	}
	
	/// <summary>
	/// C01___Card
	/// <para></para>
	/// <para>Path: /sitecore/templates/MarketingVillage/Feature/Card/C01 - Card</para>	
	/// <para>ID: 0046a26d-a5a2-48d0-82c9-573aed8d3c39</para>	
	/// </summary>
	[SitecoreType(TemplateId=IC01___CardConstants.TemplateIdString)] //, Cachable = true
	public partial class C01___Card  : GlassBase, IC01___Card 
	{
		
				/// <summary>
				/// The Has Button field.
				/// <para></para>
				/// <para>Field Type: Checkbox</para>		
				/// <para>Field ID: 4fa7b29b-5684-463a-84e9-585371b8b3a3</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IC01___CardConstants.Has_ButtonFieldName)]
				public virtual bool Has_Button  {get; set;}
		
				/// <summary>
				/// The Has SubTitle field.
				/// <para></para>
				/// <para>Field Type: Checkbox</para>		
				/// <para>Field ID: 4e40224d-f06a-4487-a624-37209dff8786</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IC01___CardConstants.Has_SubTitleFieldName)]
				public virtual bool Has_SubTitle  {get; set;}
		
				/// <summary>
				/// The Image Is Clickable field.
				/// <para></para>
				/// <para>Field Type: Checkbox</para>		
				/// <para>Field ID: dc4ce0f7-1fb6-4102-bdf8-1a411e0622ff</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IC01___CardConstants.Image_Is_ClickableFieldName)]
				public virtual bool Image_Is_Clickable  {get; set;}
		
				/// <summary>
				/// The Title Is Clickable field.
				/// <para></para>
				/// <para>Field Type: Checkbox</para>		
				/// <para>Field ID: 44519f58-8a57-422b-b17a-d247860a8828</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IC01___CardConstants.Title_Is_ClickableFieldName)]
				public virtual bool Title_Is_Clickable  {get; set;}
		
				/// <summary>
				/// The C01 Events field.
				/// <para></para>
				/// <para>Field Type: Multilist with Search</para>		
				/// <para>Field ID: 79407ee4-aca1-45bc-9125-1ea61d6041f8</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IC01___CardConstants.C01_EventsFieldName)]
				public virtual IEnumerable<Guid> C01_Events  {get; set;}
		
				/// <summary>
				/// The C01 Goals field.
				/// <para></para>
				/// <para>Field Type: Multilist with Search</para>		
				/// <para>Field ID: 43e7f6e9-a782-4455-b131-c350438c9539</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IC01___CardConstants.C01_GoalsFieldName)]
				public virtual IEnumerable<Guid> C01_Goals  {get; set;}
		
				/// <summary>
				/// The C01 Outcome field.
				/// <para></para>
				/// <para>Field Type: Multilist with Search</para>		
				/// <para>Field ID: a155ed32-1410-485c-a7bf-df3a61094ba9</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IC01___CardConstants.C01_OutcomeFieldName)]
				public virtual IEnumerable<Guid> C01_Outcome  {get; set;}
			
	}

}
namespace MarketingVillage.Feature.Card.Models
{
 	/// <summary>
	/// IC01___Card_Item Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/MarketingVillage/Feature/Card/C01 - Card Item</para>	
	/// <para>ID: e3e5a2a0-6e90-4d14-b4ef-1f1d3193da4d</para>	
	/// </summary>
	[SitecoreType(TemplateId=IC01___Card_ItemConstants.TemplateIdString )] //, Cachable = true
	public partial interface IC01___Card_Item : IGlassBase 
	{
			
					/// <summary>
					/// The Button Title field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: cd799758-e3b0-4a9a-9cb1-c2de6370388d</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IC01___Card_ItemConstants.Button_TitleFieldName)]
					string Button_Title  {get; set;}
			
					/// <summary>
					/// The Description field.
					/// <para></para>
					/// <para>Field Type: Multi-Line Text</para>		
					/// <para>Field ID: 7f8ce4b7-3421-4fe2-b86a-c1a361d8fc9b</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IC01___Card_ItemConstants.DescriptionFieldName)]
					string Description  {get; set;}
			
					/// <summary>
					/// The Destination field.
					/// <para></para>
					/// <para>Field Type: General Link</para>		
					/// <para>Field ID: 395804c6-de48-4935-b251-083a46a07b6a</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IC01___Card_ItemConstants.DestinationFieldName)]
					Link Destination  {get; set;}
			
					/// <summary>
					/// The Image field.
					/// <para></para>
					/// <para>Field Type: Image</para>		
					/// <para>Field ID: 2d402b4e-dda0-49b8-bf1f-5ccd4811480b</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IC01___Card_ItemConstants.ImageFieldName)]
					Image Image  {get; set;}
			
					/// <summary>
					/// The SubTitle field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: e9bc15cf-2bbf-49e6-9403-15c16b971321</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IC01___Card_ItemConstants.SubTitleFieldName)]
					string SubTitle  {get; set;}
			
					/// <summary>
					/// The Title field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: e08e61c4-f78e-48ce-aa57-0defa4406fc5</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IC01___Card_ItemConstants.TitleFieldName)]
					string Title  {get; set;}
			
	}
	public static partial class IC01___Card_ItemConstants{
			public const string TemplateIdString = "e3e5a2a0-6e90-4d14-b4ef-1f1d3193da4d";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "C01 - Card Item";
		
			public static readonly ID Button_TitleFieldId = new ID("cd799758-e3b0-4a9a-9cb1-c2de6370388d");
			public const string Button_TitleFieldName = "Button Title";
		
			public static readonly ID DescriptionFieldId = new ID("7f8ce4b7-3421-4fe2-b86a-c1a361d8fc9b");
			public const string DescriptionFieldName = "Description";
		
			public static readonly ID DestinationFieldId = new ID("395804c6-de48-4935-b251-083a46a07b6a");
			public const string DestinationFieldName = "Destination";
		
			public static readonly ID ImageFieldId = new ID("2d402b4e-dda0-49b8-bf1f-5ccd4811480b");
			public const string ImageFieldName = "Image";
		
			public static readonly ID SubTitleFieldId = new ID("e9bc15cf-2bbf-49e6-9403-15c16b971321");
			public const string SubTitleFieldName = "SubTitle";
		
			public static readonly ID TitleFieldId = new ID("e08e61c4-f78e-48ce-aa57-0defa4406fc5");
			public const string TitleFieldName = "Title";
			
	}
	
	/// <summary>
	/// C01___Card_Item
	/// <para></para>
	/// <para>Path: /sitecore/templates/MarketingVillage/Feature/Card/C01 - Card Item</para>	
	/// <para>ID: e3e5a2a0-6e90-4d14-b4ef-1f1d3193da4d</para>	
	/// </summary>
	[SitecoreType(TemplateId=IC01___Card_ItemConstants.TemplateIdString)] //, Cachable = true
	public partial class C01___Card_Item  : GlassBase, IC01___Card_Item 
	{
		
				/// <summary>
				/// The Button Title field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: cd799758-e3b0-4a9a-9cb1-c2de6370388d</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IC01___Card_ItemConstants.Button_TitleFieldName)]
				public virtual string Button_Title  {get; set;}
		
				/// <summary>
				/// The Description field.
				/// <para></para>
				/// <para>Field Type: Multi-Line Text</para>		
				/// <para>Field ID: 7f8ce4b7-3421-4fe2-b86a-c1a361d8fc9b</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IC01___Card_ItemConstants.DescriptionFieldName)]
				public virtual string Description  {get; set;}
		
				/// <summary>
				/// The Destination field.
				/// <para></para>
				/// <para>Field Type: General Link</para>		
				/// <para>Field ID: 395804c6-de48-4935-b251-083a46a07b6a</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IC01___Card_ItemConstants.DestinationFieldName)]
				public virtual Link Destination  {get; set;}
		
				/// <summary>
				/// The Image field.
				/// <para></para>
				/// <para>Field Type: Image</para>		
				/// <para>Field ID: 2d402b4e-dda0-49b8-bf1f-5ccd4811480b</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IC01___Card_ItemConstants.ImageFieldName)]
				public virtual Image Image  {get; set;}
		
				/// <summary>
				/// The SubTitle field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: e9bc15cf-2bbf-49e6-9403-15c16b971321</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IC01___Card_ItemConstants.SubTitleFieldName)]
				public virtual string SubTitle  {get; set;}
		
				/// <summary>
				/// The Title field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: e08e61c4-f78e-48ce-aa57-0defa4406fc5</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IC01___Card_ItemConstants.TitleFieldName)]
				public virtual string Title  {get; set;}
			
	}

}
